apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - frontend.yml
  - db/postgres-deployment.yml
  - db/postgres-service.yml
  - ../namespaces/receita.yml
