---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: receitas-app
spec:
  encryptedData:
    password: AgBaV2OMEZ2FrFQcbVdLOWzDA4R+VdAcgbDqepBYY6KcjMEfOwOXTQWA0lKoFUgJyaddi+y+hHlPuLGsRTUVRqL8IlIPSu3CGW2g8q3kzuhJa/3ZK+yhbzXkHAknYhWkFl7BtMmxEmiRBsmL1O/aSr1ufewXlH/N/snCRN7jdAEpv8LB8QYOj1VJ4q2FlWK3+evRlycEw3fahEfLUSg4Sf2dt+C62KjJ09Y4L8fCDEmga4JvHdP6yprZNXyTA5l5mw0Lek9X8loT1IbxVfnQwwcuaXeP/E0rjMziAAhX3/AXGw52wIp8TEEhlhxS7uG7353MY1V39nTtLsnenPwC9qpQqql8zQu9WglfJVHsLybecu5ThPPNUpl/ifqPp2KZhHS2IUsy2tJQW/pkHcmWQzdTAfS/knmVR5UiiAjlF5cj9069jXO3gi2f1cuXNi8lRfsJWxSV8cfVLPDyxYhWKKg5Z+OfoOff8Vi6smqSXeH5CDxGfReRNzKlhUO5JwTo/ZU5v9bPRT/DegEyXz6L+LcjMYFGeicezP7dqr2Xh7P5+tdflNMGkggRXKaBDGPb7kk8sq1Kaljzt+dZlfzbhLDJCKjvoG+/trStCL6XUrkpkHEtW5R3OL/byszJJ/Z2q4XcEoXXwtiSuIDf9OwYdIq2narm7Qa8IfpmvdHz1MSZS6gVXKMA9tpbRE35ih+3LYKrNRkLadNzUw==
    username: AgAWX4AKuQjnEBrf5t0Myk+3gnXOVquPZkVzuB+iWWDiAR6khE4NVcsJ86zPs8hDUvUBKQHMrnqVLgylgy75iHc5F6hxQk+QD2+KXKiZ4paRvWaDcqTCGn63M46t7CDGGlLM1JvvHWqlK7Ez7PNhXUyth6o5Xl8rLDlgKtox3rvsLxm82sAjh+5yJf/yQGlQPNk6JXNKceq93XRkNSMdVjhmCQTrLgIpCc/LdwgmGx0khRFV3Yc0y1/xBA4K+gcMxu/es6a8UluSgiuydKj85HTQID10b2SoaevoWQO37Q4z5MI6zKvkZI+3mg7jxmp5OnoF9iAtkiJt/1EckeCe+KqfF0GWWyqzD56zEsFHyKoWIpeRwNhIyvv9oWLUKBY4WDIvFhV6yo/GqKd+HpgRdqlPU4DQcWHvRxL/koBDICw4QkiS4tVXI701SGLseFykA0dXCKMcQqiY62ZW2dIYg4XYFRJ6fB1yYQ0Sd5bAqcMAD7VpAUwSJZLB8n9wk9C5va+Qpe8GP47XfawSuo5TOmh1TNzzDnWCsKaEb2sQNt8mOfRVCunegGW0dGYNtzQi+CRRvkwedzCigE9sd3CytnY6vKOrw8SgOxgMU0s1tdq8BS5XB52uOnjjIlMhLIXINtRqKvpMcF69XWl/ID+99BWinf29allfTDknjAgNNtZwg2sWSBH0xTkYnRIioXaIZZXKzxdK9g==
  template:
    metadata:
      name: postgres-credentials
      namespace: receitas-app
