apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-dashboard
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostSNI(`*`) && PathPrefix(`/argocd`)
      services:
        - name: argocd-server
          port: 443
          scheme: https
