apiVersion: apps/v1
kind: Deployment
metadata:
  name: receitas-app
  namespace: receitas-app
  labels:
    tier: backend
  annotations:
    description: "Backend app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receitas-app
  template:
    metadata:
      labels:
        app: receitas-app
    spec:
      containers:
        - name: receitas-app-backend
          image: ghcr.io/jaimecabrito01/Api-receitas-backend:latest
          ports:
            - containerPort: 8080

