apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - receitas-app.yml
  - deployment.yml
  - frontend.yml
  - db/postgresql.yaml
  - security/jwt-seleadsecret.yaml
  - security/postres-seleadsecret.yaml
