apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - receitas-app.yml
  - deployment.yml
  - frontend.yml
  - ingressroute.yaml
  - ingressroute-backend.yaml
  - middleware.yaml
  - db/postgresql.yaml
  - security/jwt-sealedsecret.yaml
  - security/postgres-sealedsecret.yaml
