---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: receitas-app
spec:
  encryptedData:
    password: AgC7Gwj5EdnmOWA1dOIRqb49MhKQdKFRJ0Ysk6c/UJMX9QNGDM69gNUqEXfQ4OWJTxF8izIwQzw6BcE4igGq4py7jJuB4lTgQ8Rty6nETCG0fpi2z3A9PugspPJCPvuxON5/b5i3G2gcQ6SQPMzTj8p+9ewG00vYzDSr/QGUkN7Ku/SbldQg4iCCWonx5kCl3UnWMLpDRBugFJpJh2kJgMdZXD0xurluiiJc6dKSh9FWFsg18mn0VJs9kJtyO0tIY0mCegubCIX8X3QPPYnmiTtl/pd6J2uK1yh3NjcEypxp5ixD/4ZmXzyamkUaBLzIPcrN17rZif/Vi/BWb1JyNjzerMqUz+1OfWqOtzT4FkgKC7XUBKa1umsxDlm56bLouVdBJkfZSvz2gBIt2xTKb41+nIDNcWV5VQMAAcfpHSK+tqY3iNhYT0gv6KmDbcoJB/euSX6I8XpJyEPZV+vGXrYIoxSgNYb/1Jcea98yK0DxGXVl8vDHf1w6JF2byO7p+alkDRb1hNf/3mBZtUpzSusTzU6v3RSvrB55JbIc3B7gBFd7WtUVeIKBjW8xAu1Zd+JVoqfVCK7LfP+MdXIcfXRMWZ4/3VGv9ETE/3BjvYkbACnFT817kTi7gzy+WaCm32bRk4YP/RJ4DJfy/sSb8mOHvjMk9/1YBZcDUtarkiJFwAkmlUjqFsDwqg0FRNb0LHxZIAyoPZrK3Q==
    username: AgA6zna3DXTe1eyfGtx8tTed9NtGCbwT+VnGKpwJx7XMbabHNKXX7PYSsYo9kjeHwQ3Co+EcYgioc6fGobV+Ja+mCk79Qg58pAY0RsPk+GK+kt4nf1h+o0KhfUOdI96QtOS9MaZd8Esj66sGQ0tQBvJ4D+8j87J4lNrgeBIFdh2SjXF9nINBz2K4YNpHKXSOckcVcRUczgum/O+ZTDyhhabgSxV6oi2fLQrhJTnIO2BDPOdyJTuiHxruWoJm9bB+LdSICoIJwG/3zrHitAh8jbZUDW7uXxJnGuMM/RTegdzlT0xyfEPaH5U7AQPHdS2Ffqo9Lj2EQoWvq7Gl8yvNXLQiYYECrnZvbWwR1mNlyr8C1i19RTKpES8YliJzFQRdK+By4zYCsK5RpYNEeBgJcugkJsVnzSJGNxZCPA18sIzaoMjyc2turCBRhL3OMXJ0O+310ICJJIk7sBc/NLgJgblK0fO4+iiMg1WOtabxSKF57puE4gJVzjh0g3GJToVOV3065zkOIycWtU+UedSnqoDHb2bQjCiwbMJpYzgmoQRLuMfwapQuO5u/HVnymUcjWsYyo6pzyuQGjtVDOguU0/X/0gnewmfxOcE/ej/1K4Iy1IrsupKmbylJmj8nl1GqIMx21LGaQnKLj/Yw3UFz15TKpagk3dOxr0PY+ZltaloC1lKW7P05STWDq/JcorqAp2HDBne/9Q==
  template:
    metadata:
      name: postgres-credentials
      namespace: receitas-app
