---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: receitas-app
spec:
  encryptedData:
    password: AgCmdfnAMIkDvwvhaSCBTiMj6BVXE7DClKeD5EgAPGSvxjuCMBQno8k7ahBA0oO8RbXjg/qE24bKnvJDwW3LwqWULOOyXGZ0AtqOb3ErboW7vgilyWSJTbwB0wQEZN7dWLORk6DUcqnNjW3SqUjk+mfgzJCm8440GCw2rWJWoNrYu6HsqF4yGUCPHzq2x/HG74+WVJqcitqfuAqdJTLvCv/9i90G62j1E6ApzTG5NxUUrz/ldl7VTp1Bm+X6fnt4vvZosRbCx6k8nYM4pmrlqwj/8RWyoCP5aUgLsxnt6EAqdWmOAlTmwNJ114UYI1YAMqLjdPtsr//8D9NHXrTNec0yOQn/Epeh0HOZIc5Dv70miWrSHn2/KuFsbLivpvl7c5DwvFkAx9+uf+ZRYjkkSS6qOTj87kvHFgR9CzZfyxYEQh7yN5JP3ke/ajjDMXLjfolKIcWLeB4Y5kHWTmYdrzDbFRoyN4bBp5QEq6/8mQGTSnO41VNEc6jvIUrimOzXVaS8wvIYk/SWSFmfPGf/JChOYX/xdGrwOjVqhhjO/410EzOZTFTHxaeb0HEEKeDkOIQzgCzyNy2d209tFohGNVBEFJ9TB1cC1P2Cwp57GmVwn47OsF0G27W4WGqXhh8WlpXPPafdapuZt/cFeMhOE+goU5ooFdyzwT9Mq7R6x9ZITNuY6Cd+LL0g5x675oxq38cNscLOzjhYsg==
    username: AgCFcFHy2VlwHy6mUdcMlmu9y0i+iYeUywxc3LfBXs9meXXMfJtSy2O/wYIjl2ln5jJNDLh6dKfNagbDE3yQKANhGcdTDDk/QhiBFb3Vir7H9zAFuJcZWkmzlN9rhLR/onDDZlKVHc8Mj8j4TM9HCYwcPOLBgI4hJPDc5AdidnG1UOQUC/w56BuurVBDLxSJ3hxAlZOtdecBoEuap06aXwT/Tfh8iUE/vW5qm+8GkIj8v4b91ubF/icpnVywIl1fuJTAyf9ohYv2nrcuqfXGpNpwHG8M2B3BCti4XJFCschz8TpN8V6eXMKcIvS2pLAEkT+QfKqdmkxe+YhEs8NE0Ma5xZtIViEKcsmKdBzSNECmraaaSdDCkStC6LC+i+oP+fKgQyAihNi8gB5mYb6OI5xMpXRJtx4LH7zFHhPOkCYXrUOS31nvWtgLRNejjmlASpGY/6zu7xBLyMbK7qcZrnHJlXQCL7pxYudYKfmpaAQybSXbER7e5gMBPXY9EIpeO3s5hZfzMXNWPzNXONxdHh/cDqYEuOWENgaosCVgrsWcN6KvT4vcvz7OysESZ6kAfQtKtAuuQJHImi3WOl5YOHbtxMst/oYyHVP6+FEnkTQZVYB5iDG3YinAkbweVGw4OTTqSaPCQwMd5uATzXG6ZwOvbbioz1qQWkjxWkBdJLOhArh1xTgh6pk553syw3nevdjQLdKfxg==
  template:
    metadata:
      name: postgres-credentials
      namespace: receitas-app
