---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: receitas-app
spec:
  encryptedData:
    password: AgBbsgReMfmog1c/Gj6P1GrcD+SY3PKh90hyOvQe3dA+u/+cX8CbqChD2EF1Of7QIEuYthIIBfp9Dl35vqf01eJVscRbfsGI1lDe80kzqp2/JWbYl8c5ACAEMXBD+qTX90MEIBbpObl0U00BBabqqBuR/JuR07/EfMsVClD2ToBblXCyk1CE9HtqrZzD0jpOBBgmkvGEBWIkaoezxXznfMxFc9dnYKNty6W4oyYw9sNk3FtrgLKO/y7BSBAYN3RqrCePg/a9dy7XBlyDtkYizWsi3rKD0xkV2qPg/CaMX9S+pKbE3y1/k73f1yiJgQCsta9MkseyadgKECpoq/fm1BXqR52PiVftgVB4kYnDpoxdIxCsl0jI6r6E8Xdghy3bLUMXLa0Jza9/ZVUBBeBjmkzBVhe5Bhay9HuWsHedtUbbCsYYS5uTlmCv+pRWm4weolp7QBOVrGORHj3BzIg81rNSAxakFTFPWxFZ02GRP8FQ+Ips6+Mmp2avpPwfcP9AB7GiVZY08hdn1xaGtcc3mLrClTdmY7q0Nl8XP9JC+ZitxWgBmOj/X83uF2dAQCUFWK144vJkI/TpeAyiO492gKzGgE8/o9jSl44zbJTzJ/lqt2n6qlYTllq9QWiCxARuXMGFOcvBoXpx379vb6SfECBM//3k7hrUf8Pnb3j4wys4q/hNM2NWb7ueNWE2J1pWTZcM6M7mLn76cw==
    username: AgBoLep/zknutLByaeNGG4UpJAR8rbUODacBct6FZatdaduUtMTSxdEKK9Tam+UeMf0F2RxEYIYmSjXX6hLapZ6/5No8daALAU9Yu0rMz1RLt/AQCdIC+oshucMos/arlgS8+cwn8LqkaleI68XOe4xWn5QSpfmWilfhs4AMRdQmMY3/Q5MzVAWI6z16IjUl4csd6Yl3OQV96b1fAXLEWwZJNwHfIzqNYXkKBM9c6Zl1p4mOeTc6OZDz/SXWgIjn6Pq0qqfU25sBBwgVEr6mG0xdxdFy1p4mfP5A6jn+/OOgd1H7ePcG5bZs1w0zsst0lGk2ink+O30vJvMoRmlBrEI58fpZ5BOPOWJqfKqZqIaTST9+2nEnqczyH4Xu8e+rRLacytDnMF6AK2oxI2OQH2GAYFtnxtgAb7OJffuoR7f1E0MSiFEeKgIs624CSALaj41zLbMizMdHgQ3W5oZC9sFTi7ajBsx3owFNno1kJAanwL6pfTenGIQFJWytC3pWcbQLN2RrK6cbgG+NTDp+ZC/Sbai0FVjoRm0F/L5D+v9faTSMdoUzGMYFA7jlB2ppdZAdFryarcU1tdiH04Bj/CaTQR3xLzVD3urjdB4uLsxY9/Ear2UuVcpauB0JihnBJ6imV8g2gr7U5tFgVMKA8ji1t4QgLZKPrw3vRQ5PNQsl7fjX88Q1GhXyoPf4qhqoCVyePPGAoA==
  template:
    metadata:
      name: postgres-credentials
      namespace: receitas-app
