apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: receitas-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=
